service: myserverlessproject

provider:
  name: aws
  runtime: nodejs10.x
  profile: serverlessUser

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: myserverlessprojectuploadbucket-123123
      localDir: UploadData

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myserverlessprojectuploadbucket-123123
